version: "3.9"
services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - 3200:3200
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - split-network
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - split-network
    depends_on:
      - backend

  mongo2:
    container_name: mongo2
    image: mongo
    restart: always
    command: "bash -c '/usr/bin/mongod --replSet $${MONGO_REPLICA_NAME} --journal --bind_ip_all'"
    ports:
      - "27018:27017"
    env_file:
      - ./database/.env
    networks:
      - split-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    command: "bash -c '/usr/bin/mongod --replSet $${MONGO_REPLICA_NAME} --journal --bind_ip_all'"
    ports:
      - "27017:27017"
    env_file:
      - ./database/.env
    links:
      - mongo2
    volumes:
      - ./database/rs-init.sh:/scripts/rs-init.sh
    networks:
      - split-network
  
  redis:
    container_name: redis
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"     
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    env_file:
      - ./database/redis/.env

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - '${FORWARD_AZURITE_BLOB_PORT:-10000}:10000'
    command: azurite-blob --blobHost 0.0.0.0 --disableProductStyleUrl
    volumes:
      - azurite:/data
    networks:
      - split-network
    depends_on:
      - azurite-init
  
  azurite-init:
    image: curlimages/curl:7.87.0
    entrypoint:
    - /bin/sh
    - -c
    - |
      echo "Waiting for Azurite to start..."
      while ! nc -z azurite 10000; do sleep 1; done
      curl --request PUT \
      --url 'http://azurite:10000/devstoreaccount1/split-images?restype=container&sv=2021-10-04&ss=btqf&srt=sco&st=2022-12-14T16%3A22%3A03Z&se=2119-01-15T16%3A22%3A00Z&sp=rwdxftlacup&sig=uXt%2FXqfK1iFnNeDP60UD1CwJueWVoADE9gOLqkkI3NM%3D' \
      --header 'x-ms-blob-public-access: blob'
    networks:
      - split-network

networks:
  split-network:
    driver: bridge

volumes:
  azurite:
    driver: local