version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    container_name: dc-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DB_NAME:-dc}
      MONGO_BACKEND_USER: ${DB_USER:-backend}
      MONGO_BACKEND_PASSWORD: ${DB_PASSWORD:-password}
