version: "3.9"

services:
  backend:
    build:
      context: backend # starts on backend folder instead on root
      target: local # choose development part from Dockerfile
      dockerfile: docker/local/Dockerfile

    # image name
    image: split-dev-backend

    # container name
    container_name: dev-backend

    networks:
      - split-network
    depends_on:
      - mongo

    env_file:
      - ./backend/.env

    # restart strategy
    restart: unless-stopped

    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules

    ports:
      - 3200:3200
      # debugging port
      # - 9229:9229

  frontend:
    build:
      context: frontend # to start on frontend folder
      dockerfile: docker/local/Dockerfile # path to dev Dockerfile

    # set image name
    image: split-dev-frontend

    # set container name
    container_name: dev-frontend

    networks:
      - split-network
    depends_on:
      - backend

    env_file:
      - ./frontend/.env

    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

    # restart strategy
    restart: unless-stopped

    # set ports
    ports:
      - 3000:3000

  mongo2:
    image: mongo
    restart: always
    container_name: mongo2
    networks:
      - split-network
    ports:
      - "27018:27017"
    entrypoint: "bash -c '/usr/bin/mongod --replSet $${MONGO_REPLICA_NAME} --journal --bind_ip_all'"
    env_file:
      - ./database/.env
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database/rs-init.sh:/scripts/rs-init.sh
    networks:
      - split-network
    links:
      - mongo2
    command: "bash -c '/usr/bin/mongod --replSet $${MONGO_REPLICA_NAME} --journal --bind_ip_all'"
    env_file:
      - ./database/.env
   
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"     
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    env_file:
      - ./database/redis/.env

volumes:
  redis_data:
    driver: local

# Networks
networks:
  split-network:
    driver: bridge
