version: "3.9"
services:
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - 3200:3200
    env_file:
      - ./backend/.env
    networks:
      - split-network
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    command: npm run dev
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    networks:
      - split-network
    depends_on:
      - backend
  mongo2:
    container_name: mongo2
    image: mongo
    restart: always
    command: "bash -c '/usr/bin/mongod --replSet $${MONGO_REPLICA_NAME} --journal --bind_ip_all'"
    ports:
      - "27018:27017"
    env_file:
      - ./database/.env
    networks:
      - split-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    command: "bash -c '/usr/bin/mongod --replSet $${MONGO_REPLICA_NAME} --journal --bind_ip_all'"
    ports:
      - "27017:27017"
    env_file:
      - ./database/.env
    links:
      - mongo2
    volumes:
      - ./database/rs-init.sh:/scripts/rs-init.sh
    networks:
      - split-network
  
  redis:
    container_name: redis
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"     
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    env_file:
      - ./database/redis/.env
networks:
  split-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
