{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "split.fullname" . }}
  labels:
    {{- include "split.labels" $ | nindent 4 }}
type: Opaque
data:
  FOO: {{ "BAR" | b64enc | quote }}
{{- end }}
