frontend:
  ingress:
    hosts:
      - host: split-dev.xgeeks.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - split-dev.xgeeks.com
        secretName: split-frontend-tls

  environment:
    NODE_ENV: dev

backend:
  ingress:
    hosts:
      - host: split-dev-api.xgeeks.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - split-dev-api.xgeeks.com
        secretName: split-backend-tls

  environment: 
    NODE_ENV: dev
    NEXT_PUBLIC_NEXTAUTH_URL: https://split-dev.xgeeks.com
