{{- range $service := .Values.services }}
{{- if $service.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "split.fullname" $ }}-{{ $service.name }}
  labels:
    {{- include "split.labels" $ | nindent 4 }}
type: Opaque
data:
  FOO: {{ "BAR" | b64enc | quote }}
{{- end }}
---
{{- end }}
