{{- range $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "split.fullname" $ }}-{{ $service.name }}
  labels:
    {{- include "split.labels" $ | nindent 4 }}
spec:
  type: {{ $service.service.type }}
  ports:
    - port: {{ $service.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "split.selectorLabels" $ | nindent 4 }}
---
{{- end }}
