name: Build and Deploy

on:   
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build_backend:
    name: Build backend
    uses: ./.github/workflows/build_docker.yaml
    with:
      DOCKERFILE: ./backend/Dockerfile
      REPOSITORY: backend
      ROOT: ./backend
    secrets: inherit

  build_frontend:
    name: Build frontend
    uses: ./.github/workflows/build_docker.yaml
    with:
      DOCKERFILE: ./frontend/Dockerfile
      REPOSITORY: frontend
      ROOT: ./frontend
      BUILD_ARGS: |
       "ASH=${{ vars.AZURE_STORAGE_HOSTNAME }}"
    secrets: inherit

  deploy_dev:
    name: Deploy DEV
    needs:
      - build_backend
      - build_frontend
    uses: ./.github/workflows/on_call_deploy.yaml
    with:
      ENVIRONMENT: dev
      CHART_OVERRIDE_PATH: './infrastructure/values/development.yaml'
    secrets: inherit

  deploy_prod:
    name: Deploy PROD
    needs: deploy_dev
    uses: ./.github/workflows/on_call_deploy.yaml
    with:
      ENVIRONMENT: prod
      CHART_OVERRIDE_PATH: './infrastructure/values/production.yaml'
    secrets: inherit

  pre_release:
    name: Create Pre Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deploy_dev
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RELEASE }}
        with:
          prerelease: true

  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: deploy_prod
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RELEASE }}
        with:
          publish: true
