name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT: 
        required: true
        type: string
      CHART_OVERRIDE_PATH:
        required: true
        type: string

env:
  TAG: ${{ github.sha }}
  CHART-PATH: './infrastructure/split'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with: 
          resource-group: '${{ secrets.RESOURCE_GROUP }}'
          cluster-name: '${{ secrets.CLUSTER_NAME }}'
          admin: 'false'
          use-kubelogin: 'true'

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Deploy
        run: helm upgrade --install split ${{ env.CHART-PATH }} -f ${{ inputs.CHART_OVERRIDE_PATH }} --set global.image.tag=${{ env.TAG }} --namespace=split-${{ inputs.ENVIRONMENT }} --create-namespace --atomic