name: Test

on:
    pull_request:
        branches:
            - main
            - dev

    workflow_dispatch:

jobs:
    build_test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Cache multiple paths
              uses: actions/cache@v2
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - name: npm ci and test
              run: |
                  cd backend
                  npm ci
                  npm test
            - name: npm ci and test frontend
              run: |
                  cd frontend
                  npm ci
                  npm run jest
